// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj-iS4vfs6CNSnlciAU_rhCw5OmDU3fv0',
    appId: '1:421247204466:web:90e1ac680c4ac369de16eb',
    messagingSenderId: '421247204466',
    projectId: 'learn-flutter-5eeb9',
    authDomain: 'learn-flutter-5eeb9.firebaseapp.com',
    storageBucket: 'learn-flutter-5eeb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLsnOEUo41TD5qEJdrWzcDqJ-4f4B2HU',
    appId: '1:421247204466:android:c34088daf999a2e9de16eb',
    messagingSenderId: '421247204466',
    projectId: 'learn-flutter-5eeb9',
    storageBucket: 'learn-flutter-5eeb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAveLNoHg4SKSSudftZMJKG5_K8wk_uYgU',
    appId: '1:421247204466:ios:72cbeaf077bf0297de16eb',
    messagingSenderId: '421247204466',
    projectId: 'learn-flutter-5eeb9',
    storageBucket: 'learn-flutter-5eeb9.firebasestorage.app',
    iosBundleId: 'com.example.flCredit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAveLNoHg4SKSSudftZMJKG5_K8wk_uYgU',
    appId: '1:421247204466:ios:72cbeaf077bf0297de16eb',
    messagingSenderId: '421247204466',
    projectId: 'learn-flutter-5eeb9',
    storageBucket: 'learn-flutter-5eeb9.firebasestorage.app',
    iosBundleId: 'com.example.flCredit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj-iS4vfs6CNSnlciAU_rhCw5OmDU3fv0',
    appId: '1:421247204466:web:3f09a24c293328f7de16eb',
    messagingSenderId: '421247204466',
    projectId: 'learn-flutter-5eeb9',
    authDomain: 'learn-flutter-5eeb9.firebaseapp.com',
    storageBucket: 'learn-flutter-5eeb9.firebasestorage.app',
  );
}
